INSERT INTO `reference` (`id`, `image`, `title`, `description`, `number`, `sub_number`)VALUES
(NULL, 'ref1.jpg', 'Mitex s. a.', 'Wykonanie całościowej bądź częśćiowej instalacji elektrycznej, telefonicznej, alarmowej oraz CCTV jako podwykonawca m. in.: budowy Rezydencji Prezydenckiej w Juracie-Helu, hotelu "IBIS" w Warszawie, czy Basenu Olimpijskiego w Ostrowcu Świętokrzyskim.', '1', null),
(NULL, 'ref2.jpg', 'Exbud Skanska s. a.', 'Podczas współpracy z firmą Exbud Skanska s. a. przeprowadziliśmy prace elektroinstalacyjne m. in. w czasie budowy Reifeisen Business Center w Warszawie, czy Centrum Handlowo-Usługowo-Rozrywkowego "Plaza" w Krakowie.', '2', null),
(NULL, 'ref3.jpg', 'Skanska', 'Po przejęciu Exbudu przez Skanskę nadal kontynuowaliśmy współpracę z tą firmą. Na przełomie lat 2006-2007 wykonywaliśmy roboty elektryczne podczas rozbudowy hali magazynowej "Staloproduktu" w Bochni.', '3', null),
(NULL, 'ref4.jpg', 'Miasto Kielce', 'Od 2006 roku przez dwa lata prowadziliśmy na zlecenie Prezydenta Miasta Kielce nadzór inwestorski branży elektrycznej przy realizacji szeregu inwestycji w obrębie miasta.', '4', null),
(NULL, 'ref5.jpg', 'Dorbud s. a.', 'W czasie naszej wieloletniej współpracy z firmą Dorbud, jednym z największych przedsiębiorstw budowlanych w Kielcach, wykonywaliśmy szereg prac instalacyjnych: wewnętrzych i zewnętrznych. <br> Budowa budynków mieszkalych, Kielce.', '5', null),
(NULL, 'ref6.jpg', 'Dorbud s. a.', 'W czasie naszej wieloletniej współpracy z firmą Dorbud, jednym z największych przedsiębiorstw budowlanych w Kielcach, wykonywaliśmy szereg prac instalacyjnych: wewnętrzych i zewnętrznych. <br> Budowa budynku mieszkalnego z częścią handlowo-usługową, Kielce.', '6', null),
(NULL, 'ref7.jpg', 'Dorbud s. a.', 'W czasie naszej wieloletniej współpracy z firmą Dorbud, jednym z największych przedsiębiorstw budowlanych w Kielcach, wykonywaliśmy szereg prac instalacyjnych: wewnętrzych i zewnętrznych. <br> Budowa Centrum rehabilitacyjno-sportowego, Kielce.', '7', null),
(NULL, 'ref8.jpg', 'Dorbud s. a.', 'W czasie naszej wieloletniej współpracy z firmą Dorbud, jednym z największych przedsiębiorstw budowlanych w Kielcach, wykonywaliśmy szereg prac instalacyjnych: wewnętrzych i zewnętrznych. <br> Budowa budynku mieszkalnego z częścią hadlowo-usługową, Kielce.', '8', null),
(NULL, 'ref9.jpg', 'Dorbud s. a.', 'W czasie naszej wieloletniej współpracy z firmą Dorbud, jednym z największych przedsiębiorstw budowlanych w Kielcach, wykonywaliśmy szereg prac instalacyjnych: wewnętrzych i zewnętrznych. <br> Rozbudowa i przebudowa Świętokrzyskiego Centrum Psychiatrii, Kielce.', '9', null),
(NULL, 'ref10.jpg', 'Dorbud s. a.', 'W czasie naszej wieloletniej współpracy z firmą Dorbud, jednym z największych przedsiębiorstw budowlanych w Kielcach, wykonywaliśmy szereg prac instalacyjnych: wewnętrzych i zewnętrznych. <br> Budowa wielorodzinnego budynku mieszkalnego, Kielce.', '10', null),
(NULL, 'ref11.jpg', 'Dorbud s. a.', 'W czasie naszej wieloletniej współpracy z firmą Dorbud, jednym z największych przedsiębiorstw budowlanych w Kielcach, wykonywaliśmy szereg prac instalacyjnych: wewnętrzych i zewnętrznych. <br> Remont i przebudowa budynku na Muzeum Dialogu Kultur, Kielce.', '11', null),
(NULL, 'ref12.jpg', 'Miejski Zarząd Budynków w Kielcach', 'Jako wykonawca w 2007 roku wykonywaliśmy dla Miejskiego Zarządu Budynków w Kielcach szereg prac remontowych, instalacyjnych i montażowych w dwóch budynkach przy ulicy Grunwaldzkiej w Kielcach', '12', null),
(NULL, 'ref13.jpg', 'P. P. H. U. Weprel', 'Podczas dużego projektu rewitalizacji zabytkowego centrum Kielc, jako podwykonawca firmy Weprel zajmowaliśmy się całościową instalacją oświetlenia zewnętrznego ulicy Warszawskiej.', '13', null),
(NULL, 'ref14.jpg', 'Trakt sp. z o. o.', 'Z jednym z największych w regionie przedsiębiorstw drogowych, firmš Trakt sp. z o. o. współpracowaliśmy podczas remontu ulic Gagarina i Barabasza, wykonując instalacje oświetlenia zewnętrznego ulic.', '14', null),
(NULL, 'ref15.jpg', 'Miejski Zarząd Dróg w Kielcach', 'Inwestycję za ponad ćwierć miliona złotych dla MZD w Kielcach ukończyliśmy w 2016 roku. Zlecenie dotyczyło montażu i uruchomienia ponad 130 opraw LED.', '15', null),
(NULL, 'ref161.jpg', 'Miejski Zarząd Dróg w Kielcach', 'Inwestycję za ponad 160 000 złotych dla MZD w Kielcach ukończyliśmy w 2017 roku. Zlecenie dotyczyło montażu i uruchomienia ponad 130 opraw LED.', '16', '1'),
(NULL, 'ref162.jpg', 'Miejski Zarząd Dróg w Kielcach', 'Inwestycję za ponad 160 000 złotych dla MZD w Kielcach ukończyliśmy w 2017 roku. Zlecenie dotyczyło montażu i uruchomienia ponad 130 opraw LED.', '16', '2'),
(NULL, 'ref17.jpg', 'Świętokrzyski Urząd Wojewódzki w Kielcach', 'Nadzór inwestorski w budynku zleceniodawcy.', '17', null),
(NULL, 'ref181.jpg', 'Miejski Zarząd Dróg w Kielcach', 'Szereg prac związanych z wymianš słupów oświelteniowych z montażem opraw LED, układaniem linii kablowych i uziemienia przeprowadzaliśmy dla Miejskiego Zarządu Dróg w Kielcach.', '18', '1'),
(NULL, 'ref182.jpg', 'Miejski Zarząd Dróg w Kielcach', 'Iwestycja dotyczyła instalacji w różnych częściach miasta oraz prac o zróżnicowanym charakterze, w latach 2013 - 2015.', '18', '2')


